version: '3.1'
name: captive_backend
services:
  captive_db:
    image: captive/db
    build:
      context: .
      dockerfile: ./Captive.Commands/Database.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Password1
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  # captive_api:
  #   image: captive/api
  #   build:
  #     context: .
  #     dockerfile: ./Captive.Commands/Dockerfile
  
volumes:
  db_data: