version: '3.0'

services:
   db:
     image: mysql:8.0
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: Password1
     restart: always

   captive-api:
     build: ../Captive.Commands/
     ports:
       - "8080:5000"