services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Password1
      MSSQL_SA_PASSWORD: Password1
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    volumes:
      - C:/captive:/var/opt/mssql/backup
    networks:
      - captive_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - captive_network

networks:
  captive_network:
    driver: bridge



    